to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/urls.py
from django.urls import path, include

from .views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    task_toggle_status_view,
    TaskDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("create_task/", TaskCreateView.as_view(), name="task-create"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("tags/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path('task/<int:pk>/toggle-status/', task_toggle_status_view, name='task-toggle-status'),
]

app_name = "todo"

todo/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(blank=True, null=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", blank=True)

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

todo/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .models import Tag, Task


class TaskListView(ListView):
    model = Task
    template_name = "to_do/index.html"
    context_object_name = "task_list_all"

    def get_queryset(self):
        return Task.objects.order_by('done', 'deadline')


class TagListView(ListView):
    model = Tag
    context_object_name = "tag_list_all"
    template_name = "to_do/tag_list.html"


class TaskCreateView(CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")
    template_name = "to_do/task_form.html"


class TaskUpdateView(UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:index")
    template_name = "to_do/task_form.html"

class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")
    template_name = "to_do/delete_confirm.html"


class TagCreateView(CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "to_do/tag_form.html"


class TagUpdateView(UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "to_do/tag_form.html"


class TagDeleteView(DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")
    template_name = "to_do/delete_confirm.html"

def task_toggle_status_view(request, pk):
    if request.method == 'POST':
        task = get_object_or_404(Task, pk=pk)
        task.done = not task.done
        task.save()
        return redirect("todo:index")

templates/base.html
<html lang="en">
<head>
  {% block title %}
    <title>Perfect ToDo app</title>
  {% endblock %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">
  <div class="row">
  <div class="col-sm-3">  
    {% block sidebar %}
      {% include "includes/sidebar.html" %}
    {% endblock %}
  </div>
  <div class="col-sm-9">
    {% block content %}
    {% endblock %}
  </div>
  </div>
</div>

</body>
</html>

templates/includes/sidebar.html
<div class="btn-group-vertical">

    <a href="{% url 'todo:index' %}" class="btn btn-light btn-lg active" role="button" aria-pressed="true">Home</a>
    <a href="{% url 'todo:tag-list' %}" class="btn btn-light btn-lg active" role="button" aria-pressed="true">Tags</a>

</div>

templates/to_do/delete_confirm.html
{% extends "base.html" %}
{% block content %}
  <h1>Are you sure?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="Submit" value="Yes, delete" class="danger btn-default">
  </form>

{% endblock %}

templates/to_do/index.html
{% extends "base.html" %}

{% block content %}
    <h1>
      To-Do List
      <a style="float: right" href="{% url 'todo:task-create'%}" class="btn btn-primary"> Add Task </a>
    </h1>
    {% for task in task_list_all %}
      <div class="card text-white bg-dark mb-3">
        <div class="card-body">
          <form action="{% url 'todo:task-toggle-status' task.id %}" method="post">
            {% csrf_token %}
            {% if task.done %}
              <button type="submit" class="btn btn-danger" style="float: right">
                Undo
              </button>
            {% else %}
              <button type="submit" class="btn btn-success" style="float: right">
                Complete
              </button>
            {% endif %}
          </form>
          <h6 style="color: {% if task.done %}green{% else %}red{% endif %}">
            {{ task.content }} 
            {% if task.done %}
              <p>Done
            {% else %}
              Not done
            {% endif %}
          </h6>
          <p>{{ task.deadline }}</p>
          <p> <b>Tags</b>:
          {% for tag in task.tags.all %}
            {{ tag.name }},
          {% endfor %}
          <a href="{% url "todo:task-update" pk=task.id%} " class="btn btn-outline-warning">
            update task
          </a>
          <a href="{% url "todo:task-delete" pk=task.id%} " class="btn btn-outline-danger">
            delete task
          </a></p>
        </div>
      </div>
    {% endfor %}
{% endblock %}

templates/to_do/tag_delete_confirm.html
{% extends "base.html" %}
{% block content %}
  <h1>Are you sure?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="Submit" value="Yes, delete" class="danger btn-default">
  </form>

{% endblock %}

templates/to_do/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>Add new tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/to_do/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>All tags
  <a style="float: right" href="{% url 'todo:tag-create'%}" class="btn btn-primary"> Add new tag </a>
    </h1>
  </h1>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Tag</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>

      {% for tag in tag_list_all %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a href="{% url "todo:tag-update" pk=tag.id%} " class="btn btn-warning">
              UPDATE
            </a>
          </td>
          <td>
            <a href="{% url "todo:tag-delete" pk=tag.id%}" class="btn btn-danger">
              DELETE
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
{% endblock %}

templates/to_do/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>Add new task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
  </form>
{% endblock %}